#!/usr/bin/env bash
# =============================================================================
# Clean Stage B runs so the next matrix run starts fresh at version_0.
#
# Removes (or backs up) everything that accumulates across Stage B runs and
# would otherwise confuse the version-aware aggregator:
#   - the whole Stage B group dir (<LOG_DIR>/stage_b/<ename>/version_* for all
#     four experiments) -- checkpoints, metrics.csv, resolved_config.yaml,
#     diagnostics/, tables/
#   - generated sweep override yamls (configs/stage_b/sweeps/) -- regenerated
#     by run_stage_b_matrix.sh on the next run
#   - the aggregate output (logs/stage_b/aggregate/) -- regenerated by
#     aggregate_stage_b.sh
#
# WHY: the lambda sweep was previously a no-op, so E1/E3 sweep versions all ran
# at lambda_id=0.05 and are indistinguishable from base runs.  Re-running on
# top of them leaves stale versions whose resolved_config.yaml still reads
# LAMBDA_ID=0.05; the version-aware resolver would then label some sweeps as
# base and dedup-collide them with the real base.  A clean restart avoids that.
#
# Old runs are MOVED to a timestamped backup by default (reversible).  Pass
# --delete to hard-delete instead (frees disk; checkpoints are large).
#
# Usage:
#   bash scripts/stage_b/clean_restart.sh             # backup old runs (default)
#   bash scripts/stage_b/clean_restart.sh --dry-run   # show what would happen
#   bash scripts/stage_b/clean_restart.sh --delete    # hard-delete, no backup
#   bash scripts/stage_b/clean_restart.sh --yes       # skip confirmation prompt
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

DELETE=0
DRY=0
ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    --delete) DELETE=1 ;;
    --dry-run) DRY=1 ;;
    --yes|-y) ASSUME_YES=1 ;;
    *) echo "[ERROR] unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# Resolve the Stage B group root: <LOG_DIR>/<EXPERIMENT_GROUP>.
# Mirrors the config merge in aggregate_stage_b.sh / resolve_run_specs.py.
GROUP_DIR="$(python - <<'PY'
from pathlib import Path
from omegaconf import OmegaConf
from src.config import resolve_config_path, load_yaml_config, DEFAULT_BASE_CONFIG
cfg = load_yaml_config(DEFAULT_BASE_CONFIG)
lp = resolve_config_path("configs/local_paths.yaml")
if lp.exists():
    cfg = OmegaConf.merge(cfg, OmegaConf.load(lp))
cfg = OmegaConf.merge(cfg, OmegaConf.load("configs/stage_b/base_regression_only.yaml"))
log_dir = getattr(cfg, "LOG_DIR", None)
if not log_dir:
    raise SystemExit("[ERROR] LOG_DIR not set in local_paths.yaml")
root = Path(log_dir)
if not root.is_absolute():
    root = Path.cwd() / root
group = str(getattr(cfg, "EXPERIMENT_GROUP", "default"))
print(root / group)
PY
)"

SWEEPS_DIR="configs/stage_b/sweeps"
AGG_DIR="logs/stage_b/aggregate"

# Collect existing targets.
RUN_TARGETS=()
REGEN_TARGETS=()
[[ -d "$GROUP_DIR" ]] && RUN_TARGETS+=("$GROUP_DIR")
[[ -d "$SWEEPS_DIR" ]] && REGEN_TARGETS+=("$SWEEPS_DIR")
[[ -d "$AGG_DIR" ]] && REGEN_TARGETS+=("$AGG_DIR")

if [[ ${#RUN_TARGETS[@]} -eq 0 && ${#REGEN_TARGETS[@]} -eq 0 ]]; then
  echo "[CLEAN] nothing to clean -- no Stage B runs, sweeps, or aggregate found."
  echo "[CLEAN] next: bash scripts/stage_b/run_stage_b_matrix.sh"
  exit 0
fi

# Describe the plan.
echo "[CLEAN] Stage B group dir: $GROUP_DIR"
if [[ ${#RUN_TARGETS[@]} -gt 0 ]]; then
  if [[ "$DELETE" -eq 1 ]]; then
    echo "[CLEAN] runs:      HARD DELETE"
  else
    ts="$(date +%Y%m%d_%H%M%S)"
    BACKUP_DIR="$(dirname "$GROUP_DIR")/stage_b_archive_${ts}"
    echo "[CLEAN] runs:      BACKUP -> $BACKUP_DIR"
  fi
fi
for t in "${REGEN_TARGETS[@]}"; do
  echo "[CLEAN] regen:     rm $t  (regenerated on next run)"
done

if [[ "$DRY" -eq 1 ]]; then
  echo "[CLEAN] --dry-run: no changes made."
  exit 0
fi

# Confirm before touching anything (unless --yes).
if [[ "$ASSUME_YES" -ne 1 ]]; then
  echo ""
  read -r -p "Proceed? [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "[CLEAN] aborted."; exit 1; }
fi

# Backup or delete the run dir.
if [[ ${#RUN_TARGETS[@]} -gt 0 ]]; then
  if [[ "$DELETE" -eq 1 ]]; then
    rm -rf "$GROUP_DIR"
    echo "[CLEAN] deleted: $GROUP_DIR"
  else
    mkdir -p "$(dirname "$BACKUP_DIR")"
    mv "$GROUP_DIR" "$BACKUP_DIR"
    echo "[CLEAN] backed up: $GROUP_DIR -> $BACKUP_DIR"
  fi
fi

# Sweeps + aggregate are regenerated; just remove them.
for t in "${REGEN_TARGETS[@]}"; do
  rm -rf "$t"
  echo "[CLEAN] removed: $t"
done

echo ""
echo "[CLEAN] done.  Stage B will restart from version_0 on the next run."
echo ""
echo "Next steps (run on the server):"
echo "  git pull origin dev                            # ensure fixes are present"
echo "  bash scripts/stage_b/run_stage_b_matrix.sh     # full matrix + sweeps + diagnostics"
echo "  bash scripts/stage_b/aggregate_stage_b.sh      # version-aware aggregation"
