
# server/src/utils/visualize.py

import os
import types

import numpy as np
import csv
import glob

try:
    import torch
except ImportError:
    torch = None

try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None

try:
    from sklearn.manifold import TSNE
    from sklearn.decomposition import PCA
    from sklearn.preprocessing import LabelEncoder
except ImportError:
    TSNE = None
    PCA = None
    LabelEncoder = None

try:
    import cv2
except ImportError:
    cv2 = None


def _require_cv2():
    if cv2 is None:
        raise ImportError("OpenCV (cv2) is required for image attribution visualizations.")


def _require_matplotlib():
    if plt is None:
        raise ImportError("matplotlib is required for plotting visualizations.")


def _require_sklearn():
    if TSNE is None or PCA is None or LabelEncoder is None:
        raise ImportError("scikit-learn is required for embedding visualizations.")


def _as_numpy(values):
    if torch is not None and isinstance(values, torch.Tensor):
        values = values.detach().cpu()
        if values.is_floating_point():
            values = values.float()
        return values.numpy()
    return np.asarray(values)


def _safe_corrcoef(x, y):
    if len(x) < 2:
        return np.nan
    if np.std(x) < 1e-8 or np.std(y) < 1e-8:
        return np.nan
    return float(np.corrcoef(x, y)[0, 1])


def export_prediction_table(preds, targets, subject_ids, save_path):
    preds = _as_numpy(preds).reshape(-1)
    targets = _as_numpy(targets).reshape(-1)
    subject_ids = list(subject_ids)

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    with open(save_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["subject_id", "true_bdi", "pred_bdi", "residual", "abs_error"])
        for subject_id, target, pred in zip(subject_ids, targets, preds):
            residual = float(pred - target)
            writer.writerow([
                subject_id,
                float(target),
                float(pred),
                residual,
                abs(residual),
            ])


def select_attribution_subjects(prediction_csv, strategy="high_error", num_samples=10):
    """Select subject IDs for attribution diagnostics from prediction CSV.

    Args:
        prediction_csv: CSV generated by ``export_prediction_table``.
        strategy: ``high_error``, ``low_error``, or ``severity_balanced``.
        num_samples: Maximum number of subject IDs to return.

    Returns:
        List of subject IDs ordered by the requested strategy.
    """
    if not prediction_csv or not os.path.exists(prediction_csv):
        return []

    with open(prediction_csv, "r", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    parsed = []
    for row in rows:
        try:
            parsed.append({
                "subject_id": row["subject_id"],
                "true_bdi": float(row["true_bdi"]),
                "abs_error": float(row["abs_error"]),
            })
        except (KeyError, ValueError):
            continue

    if strategy == "low_error":
        parsed.sort(key=lambda item: item["abs_error"])
        return [item["subject_id"] for item in parsed[:num_samples]]

    if strategy == "severity_balanced":
        if not parsed:
            return []
        parsed.sort(key=lambda item: item["true_bdi"])
        buckets = np.array_split(parsed, min(num_samples, 3))
        selected = []
        per_bucket = max(1, int(np.ceil(num_samples / len(buckets))))
        for bucket in buckets:
            bucket_items = list(bucket)
            bucket_items.sort(key=lambda item: item["abs_error"], reverse=True)
            selected.extend(item["subject_id"] for item in bucket_items[:per_bucket])
        return selected[:num_samples]

    parsed.sort(key=lambda item: item["abs_error"], reverse=True)
    return [item["subject_id"] for item in parsed[:num_samples]]


def plot_regression_diagnostics(preds, targets, subject_ids, save_dir, stage, epoch=None, max_score=63, class_step=2):
    """
    Generate objective regression diagnostics:
    1. true-vs-predicted scatter
    2. residual-vs-score plot
    3. residual histogram
    4. MAE by BDI score bins
    """
    _require_matplotlib()
    preds = _as_numpy(preds).astype(float).reshape(-1)
    targets = _as_numpy(targets).astype(float).reshape(-1)
    residuals = preds - targets
    abs_errors = np.abs(residuals)

    if len(preds) == 0:
        return

    os.makedirs(save_dir, exist_ok=True)
    suffix = f"{stage}_epoch_{epoch}" if epoch is not None else stage

    rmse = float(np.sqrt(np.mean(residuals ** 2)))
    mae = float(np.mean(abs_errors))
    pearson = _safe_corrcoef(preds, targets)

    fig, axes = plt.subplots(2, 2, figsize=(14, 11))
    ax_scatter, ax_residual, ax_hist, ax_bins = axes.ravel()

    ax_scatter.scatter(targets, preds, s=42, alpha=0.75, edgecolors="none")
    ax_scatter.plot([0, max_score], [0, max_score], linestyle="--", color="black", linewidth=1.2)
    ax_scatter.set_xlim(0, max_score)
    ax_scatter.set_ylim(0, max_score)
    ax_scatter.set_xlabel("True BDI")
    ax_scatter.set_ylabel("Predicted BDI")
    ax_scatter.set_title("True vs Predicted")
    ax_scatter.text(
        0.04,
        0.96,
        f"RMSE={rmse:.2f}\nMAE={mae:.2f}\nPearson={pearson:.3f}" if np.isfinite(pearson)
        else f"RMSE={rmse:.2f}\nMAE={mae:.2f}\nPearson=N/A",
        transform=ax_scatter.transAxes,
        va="top",
        bbox=dict(facecolor="white", alpha=0.82, edgecolor="none")
    )
    ax_scatter.grid(True, linestyle=":", alpha=0.45)

    ax_residual.axhline(0, linestyle="--", color="black", linewidth=1.0)
    ax_residual.scatter(targets, residuals, s=38, alpha=0.72, edgecolors="none")
    ax_residual.set_xlabel("True BDI")
    ax_residual.set_ylabel("Prediction Residual (Pred - True)")
    ax_residual.set_title("Residuals Across Severity")
    ax_residual.grid(True, linestyle=":", alpha=0.45)

    ax_hist.hist(residuals, bins=min(20, max(6, len(residuals) // 2)), alpha=0.8)
    ax_hist.axvline(0, linestyle="--", color="black", linewidth=1.0)
    ax_hist.set_xlabel("Residual")
    ax_hist.set_ylabel("Count")
    ax_hist.set_title("Residual Distribution")
    ax_hist.grid(True, linestyle=":", alpha=0.35)

    bin_edges = np.arange(0, max_score + class_step, class_step)
    if bin_edges[-1] < max_score:
        bin_edges = np.append(bin_edges, max_score)

    bin_centers = []
    bin_mae = []
    bin_counts = []
    for left, right in zip(bin_edges[:-1], bin_edges[1:]):
        if right == bin_edges[-1]:
            mask = (targets >= left) & (targets <= right)
        else:
            mask = (targets >= left) & (targets < right)
        if np.any(mask):
            bin_centers.append((left + right) / 2)
            bin_mae.append(float(np.mean(abs_errors[mask])))
            bin_counts.append(int(mask.sum()))

    ax_bins.bar(bin_centers, bin_mae, width=max(1.0, class_step * 0.8), alpha=0.8)
    for x, y, count in zip(bin_centers, bin_mae, bin_counts):
        ax_bins.text(x, y, str(count), ha="center", va="bottom", fontsize=8)
    ax_bins.set_xlabel("BDI Score Bin Center")
    ax_bins.set_ylabel("MAE")
    ax_bins.set_title("MAE by BDI Severity Bin (labels show sample count)")
    ax_bins.grid(True, axis="y", linestyle=":", alpha=0.45)

    fig.suptitle(f"{stage.upper()} Regression Diagnostics" + (f" - Epoch {epoch}" if epoch is not None else ""))
    plt.tight_layout()
    save_path = os.path.join(save_dir, f"{suffix}_regression_diagnostics.png")
    plt.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close()

    export_prediction_table(
        preds=preds,
        targets=targets,
        subject_ids=subject_ids,
        save_path=os.path.join(save_dir, f"{suffix}_predictions.csv")
    )
    print(f"[DIAGNOSIS] {stage} 回归诊断图与预测表已输出至: {save_dir}")


def plot_tsne_disentanglement(features, subject_ids, bdi_scores, save_dir, epoch=0):
    """
    诊断需求 1：表征空间解耦体检（验证模型是否记住了人脸/发生数据泄露）

    原理：
        如果模型主要记忆受试者身份，图 A (Subject ID) 通常会呈现按人聚类的簇，而图 B (BDI) 缺少连续结构；
        如果模型学习到更稳定的抑郁表征，图 A 不应被身份明显分隔，图 B 的颜色应呈现相对平滑的连续变化。
    """
    _require_matplotlib()
    _require_sklearn()
    features = _as_numpy(features)
    bdi_scores = _as_numpy(bdi_scores)

    # 防御 PyTorch Lightning 的 Sanity Check (健全性检查) 阶段
    # 当全量样本数极少（如空跑时只有 2 个）时，t-SNE 毫无物理意义且会引发数学报错，直接安全返回
    n_samples = len(features)
    if n_samples < 10:
        print(
            f"[DIAGNOSIS] 当前全量验证样本数过少 ({n_samples} < 10)，判定处于验证集健全性检查阶段，已自动跳过 t-SNE 绘图。")
        return

    os.makedirs(save_dir, exist_ok=True)

    # 1. 降维计算 (自适应 perplexity，防止样本过少时崩溃)
    perplexity = min(30, max(5, len(features) // 4))
    # 确保在任何小样本极端实验下，perplexity 必须严格小于样本总数 n_samples
    if perplexity >= n_samples:
        perplexity = max(1, n_samples - 1)

    tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity, max_iter=1000)
    embeddings_2d = tsne.fit_transform(features)

    # 2. 对受试者字符串 ID 进行离散编码
    le = LabelEncoder()
    id_labels = le.fit_transform(subject_ids)

    # 3. 建立高清双子图
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 8))

    # 子图 A：按受试者身份染色。理想情况下，同一身份不应形成明显孤立簇。
    scatter1 = ax1.scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=id_labels, cmap='tab20', alpha=0.75,
                           edgecolors='none', s=45)
    ax1.set_title(f"Space Colored by Subject ID (Epoch {epoch})\n[Ideal: Blended / Bad: Clustered by Face ID]")
    ax1.set_xlabel("t-SNE Component 1")
    ax1.set_ylabel("t-SNE Component 2")
    if len(np.unique(id_labels)) <= 20:
        fig.colorbar(scatter1, ax=ax1, label='Encoded Subject Identity')

    # 子图 B：按真实的 BDI 抑郁分数染色 (理想状态：平滑演变的色谱)
    scatter2 = ax2.scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=bdi_scores, cmap='jet', alpha=0.75,
                           edgecolors='none', s=45)
    ax2.set_title(f"Space Colored by BDI Score (Epoch {epoch})\n[Ideal: Continuous Gradation / Bad: Chaotic Chaos]")
    ax2.set_xlabel("t-SNE Component 1")
    ax2.set_ylabel("t-SNE Component 2")
    fig.colorbar(scatter2, ax=ax2, label='True BDI Score')

    plt.tight_layout()
    save_path = os.path.join(save_dir, f"tsne_disentanglement_epoch_{epoch}.png")
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"[DIAGNOSIS] t-SNE 身份解耦体检图已输出至: {save_path}")


def plot_embedding_diagnostics(features, subject_ids, bdi_scores, save_dir, epoch=0):
    """Plot PCA, t-SNE, and optional UMAP views of the validation embedding space."""
    _require_matplotlib()
    _require_sklearn()
    features = _as_numpy(features)
    bdi_scores = _as_numpy(bdi_scores).reshape(-1)
    n_samples = len(features)
    if n_samples < 3:
        print(f"[DIAGNOSIS] 样本数过少 ({n_samples} < 3)，跳过表征空间诊断图。")
        return

    os.makedirs(save_dir, exist_ok=True)
    le = LabelEncoder()
    id_labels = le.fit_transform(subject_ids)

    projections = []
    pca = PCA(n_components=2, random_state=42)
    projections.append(("PCA", pca.fit_transform(features)))

    if n_samples >= 10:
        perplexity = min(30, max(5, n_samples // 4))
        perplexity = min(perplexity, n_samples - 1)
        tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity, max_iter=1000)
        projections.append(("t-SNE", tsne.fit_transform(features)))

    try:
        import umap
        n_neighbors = min(15, max(2, n_samples - 1))
        reducer = umap.UMAP(n_components=2, n_neighbors=n_neighbors, random_state=42)
        projections.append(("UMAP", reducer.fit_transform(features)))
    except Exception:
        pass

    fig, axes = plt.subplots(len(projections), 2, figsize=(14, 6 * len(projections)))
    if len(projections) == 1:
        axes = np.asarray([axes])

    for row_idx, (name, coords) in enumerate(projections):
        ax_id, ax_bdi = axes[row_idx]
        scatter_id = ax_id.scatter(coords[:, 0], coords[:, 1], c=id_labels, cmap="tab20", s=38, alpha=0.75)
        ax_id.set_title(f"{name} Colored by Subject ID")
        ax_id.set_xlabel(f"{name} 1")
        ax_id.set_ylabel(f"{name} 2")
        ax_id.grid(True, linestyle=":", alpha=0.35)
        if len(np.unique(id_labels)) <= 20:
            fig.colorbar(scatter_id, ax=ax_id, label="Subject ID")

        scatter_bdi = ax_bdi.scatter(coords[:, 0], coords[:, 1], c=bdi_scores, cmap="viridis", s=38, alpha=0.78)
        ax_bdi.set_title(f"{name} Colored by BDI Score")
        ax_bdi.set_xlabel(f"{name} 1")
        ax_bdi.set_ylabel(f"{name} 2")
        ax_bdi.grid(True, linestyle=":", alpha=0.35)
        fig.colorbar(scatter_bdi, ax=ax_bdi, label="BDI")

    plt.tight_layout()
    save_path = os.path.join(save_dir, f"embedding_diagnostics_epoch_{epoch}.png")
    plt.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close()
    print(f"[DIAGNOSIS] 表征空间 PCA/t-SNE/UMAP 对照图已输出至: {save_path}")


def plot_temporal_gating_weights(trend_weights, seasonal_weights, moving_avg_kernels, save_path, video_id="sample"):
    """
    诊断需求 2：时序偏好体检（监控多尺度门控网络的权重演变特征）

    验证模型在时间轴上到底是在关注长程基调（Trend），还是在捕获突变的微表情（Seasonal），
    以及在不同的阶段倾向于选择哪种尺度的滤波器核。
    """
    _require_matplotlib()
    trend_weights = _as_numpy(trend_weights)
    seasonal_weights = _as_numpy(seasonal_weights)

    seq_len, num_scales = trend_weights.shape
    time_axis = np.arange(seq_len)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 9), sharex=True)

    # 绘制 Trend Track 门控尺度演变
    for i in range(num_scales):
        ax1.plot(time_axis, trend_weights[:, i], label=f'Kernel Size: {moving_avg_kernels[i]}', alpha=0.8,
                 linewidth=1.8)
    ax1.set_title(f"Video [{video_id}] - Trend Route Gating Weights Over Time Steps (Slow Channel)")
    ax1.set_ylabel("Softmax Distribution")
    ax1.grid(True, linestyle=':', alpha=0.6)
    ax1.legend(loc='upper right')

    # 绘制 Seasonal Track 门控尺度演变
    for i in range(num_scales):
        ax2.plot(time_axis, seasonal_weights[:, i], label=f'Kernel Size: {moving_avg_kernels[i]}', alpha=0.8,
                 linewidth=1.8)
    ax2.set_title(f"Video [{video_id}] - Seasonal Route Gating Weights Over Time Steps (Fast Channel)")
    ax2.set_xlabel("Sequence Frame Index")
    ax2.set_ylabel("Softmax Distribution")
    ax2.grid(True, linestyle=':', alpha=0.6)
    ax2.legend(loc='upper right')

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()


def plot_temporal_gating_summary(trend_weights, seasonal_weights, moving_avg_kernels, save_path, epoch=0):
    """Plot validation-level mean gating weights and entropy for temporal routes."""
    _require_matplotlib()
    trend_weights = _as_numpy(trend_weights)
    seasonal_weights = _as_numpy(seasonal_weights)
    if trend_weights.size == 0 or seasonal_weights.size == 0:
        return

    trend_mean = trend_weights.mean(axis=(0, 1))
    seasonal_mean = seasonal_weights.mean(axis=(0, 1))
    trend_entropy = -np.sum(trend_weights * np.log(trend_weights + 1e-8), axis=-1).mean()
    seasonal_entropy = -np.sum(seasonal_weights * np.log(seasonal_weights + 1e-8), axis=-1).mean()

    x = np.arange(len(moving_avg_kernels))
    width = 0.36

    fig, (ax_bar, ax_text) = plt.subplots(1, 2, figsize=(13, 5))
    ax_bar.bar(x - width / 2, trend_mean, width, label="Trend")
    ax_bar.bar(x + width / 2, seasonal_mean, width, label="Seasonal")
    ax_bar.set_xticks(x)
    ax_bar.set_xticklabels([str(k) for k in moving_avg_kernels])
    ax_bar.set_xlabel("Moving Average Kernel")
    ax_bar.set_ylabel("Mean Gate Weight")
    ax_bar.set_title(f"Validation Mean Temporal Gates (Epoch {epoch})")
    ax_bar.grid(True, axis="y", linestyle=":", alpha=0.4)
    ax_bar.legend()

    ax_text.axis("off")
    ax_text.text(
        0.02,
        0.82,
        "Gating Entropy\n\n"
        f"Trend: {trend_entropy:.3f}\n"
        f"Seasonal: {seasonal_entropy:.3f}\n\n"
        "Higher entropy means the gate uses multiple temporal scales.\n"
        "Very low entropy may indicate premature route collapse.",
        fontsize=12,
        va="top"
    )

    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=170, bbox_inches="tight")
    plt.close()


def plot_training_curves_from_csv(log_dir, save_dir=None):
    """Plot training curves from PyTorch Lightning CSVLogger metrics."""
    _require_matplotlib()
    metrics_path = os.path.join(log_dir, "metrics.csv")
    if not os.path.exists(metrics_path):
        candidates = glob.glob(os.path.join(log_dir, "**", "metrics.csv"), recursive=True)
        if not candidates:
            print(f"[DIAGNOSIS] 未找到 metrics.csv，跳过训练曲线绘制: {log_dir}")
            return
        metrics_path = candidates[0]

    save_dir = save_dir or os.path.join(log_dir, "plots")
    os.makedirs(save_dir, exist_ok=True)

    with open(metrics_path, "r", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows or "epoch" not in rows[0]:
        print(f"[DIAGNOSIS] metrics.csv 缺少 epoch 列，跳过训练曲线绘制: {metrics_path}")
        return

    available_columns = set(rows[0].keys())

    def epoch_mean_series(column):
        values_by_epoch = {}
        for row in rows:
            raw_epoch = row.get("epoch", "")
            raw_value = row.get(column, "")
            if raw_epoch == "" or raw_value == "":
                continue
            try:
                epoch = int(float(raw_epoch))
                value = float(raw_value)
            except ValueError:
                continue
            values_by_epoch.setdefault(epoch, []).append(value)

        if not values_by_epoch:
            return [], []
        epochs = sorted(values_by_epoch)
        means = [float(np.mean(values_by_epoch[epoch])) for epoch in epochs]
        return epochs, means

    groups = {
        "losses": [
            "train_reg_loss",
            "train_score_loss",
            "train_mse_loss",
            "train_ccc_loss",
            "train_dist_loss",
            "train_cls_loss",
            "train_con_loss",
            "val_reg_loss",
            "val_score_loss",
            "val_mse_loss",
            "val_ccc_loss",
        ],
        "metrics": [
            "train_RMSE_epoch",
            "train_MAE_epoch",
            "train_CCC_epoch",
            "val_RMSE_epoch",
            "val_MAE_epoch",
            "val_CCC_epoch",
            "train_pred_mean",
            "train_pred_std",
            "val_pred_mean",
            "val_pred_std",
            "train_pred_norm_mean",
            "val_pred_norm_mean",
        ],
        "uw_weights": ["uw_weight_reg", "uw_weight_cls", "uw_weight_con"],
        "learning_rate": [col for col in available_columns if "lr" in col.lower()],
    }

    fig, axes = plt.subplots(2, 2, figsize=(16, 10))
    for ax, (title, group_columns) in zip(axes.ravel(), groups.items()):
        plotted = False
        for col in group_columns:
            if col not in available_columns:
                continue
            epochs, means = epoch_mean_series(col)
            if not epochs:
                continue
            ax.plot(epochs, means, marker="o", linewidth=1.8, label=col)
            plotted = True
        ax.set_title(title.replace("_", " ").title())
        ax.set_xlabel("Epoch")
        ax.grid(True, linestyle=":", alpha=0.4)
        if plotted:
            ax.legend(fontsize=8)
        else:
            ax.text(0.5, 0.5, "No data", ha="center", va="center", transform=ax.transAxes)

    plt.tight_layout()
    save_path = os.path.join(save_dir, "training_curves.png")
    plt.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close()
    print(f"[DIAGNOSIS] 训练曲线已输出至: {save_path}")


class FeatureGradCAM:
    """
    诊断需求 3：空间局部关注（Grad-CAM 特征热力图提取引擎）
    专为提取层设计，通过注册 Hook 拦截指定卷积层的特征流与梯度流。
    """

    def __init__(self, target_layer):
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None
        self.handlers = []
        self._register_hooks()

    def _register_hooks(self):
        def forward_hook(module, input, output):
            self.activations = output.detach()

        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0].detach()

        self.handlers.append(self.target_layer.register_forward_hook(forward_hook))
        self.handlers.append(self.target_layer.register_full_backward_hook(backward_hook))

    def __call__(self, model_output, single_frame_shape, original_bgr=None):
        """
        根据反向传播计算特征图权重
        """
        _require_cv2()
        # 回归模型以输出均值触发反向，计算敏感度
        model_output.mean().backward(retain_graph=True)

        gradients = _as_numpy(self.gradients)[0]  # [C, h, w]
        activations = _as_numpy(self.activations)[0]  # [C, h, w]

        weights = np.mean(gradients, axis=(1, 2))  # [C]
        cam = np.zeros(activations.shape[1:], dtype=np.float32)

        for i, w in enumerate(weights):
            cam += w * activations[i]

        cam = np.maximum(cam, 0)  # ReLU 过滤
        if np.max(cam) - np.min(cam) > 1e-8:
            cam = (cam - np.min(cam)) / (np.max(cam) - np.min(cam))
        else:
            cam = np.zeros_like(cam)

        h, w = single_frame_shape if original_bgr is None else original_bgr.shape[:2]
        heatmap = cv2.resize(cam, (w, h))
        heatmap_img = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)

        if original_bgr is not None:
            return cv2.addWeighted(original_bgr, 0.6, heatmap_img, 0.4, 0)
        return heatmap_img

    def remove(self):
        for h in self.handlers:
            h.remove()




class BackboneGradCAM:
    """
    方案一：Grad-CAM 视觉归因投影引擎 (适配 iresnet50 最后一层)
    """

    def __init__(self, model_instance, target_layer):
        self.model = model_instance
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None
        self.handlers = []
        self._register_hooks()

    def _register_hooks(self):
        def forward_hook(module, input, output):
            self.activations = output.detach()

        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0].detach()

        # 挂载钩子拦截特征流与梯度流
        self.handlers.append(self.target_layer.register_forward_hook(forward_hook))
        self.handlers.append(self.target_layer.register_full_backward_hook(backward_hook))

    def generate_heatmap(self, loss_target, raw_frame_bgr):
        """
        计算梯度并执行空间对称加权求和，投射回原始图像
        """
        _require_cv2()
        self.model.zero_grad()
        loss_target.backward(retain_graph=True)

        # 提取拦截到的梯度与特征图 [1, C, h, w]
        gradients = _as_numpy(self.gradients[0])
        activations = _as_numpy(self.activations[0])

        # 兼容 ViT 输出：检测 Token 序列并恢复为二维空间网格。
        # 如果 gradients 维度为 2，且第一维刚好等于 ViT 的 Token 总数（如 50, 197 等），说明进入了 Transformer 模式
        if gradients.ndim == 2 and gradients.shape[0] in [50, 197, 257]:
            num_tokens = gradients.shape[0]
            channels = gradients.shape[1]
            # 计算二维栅格尺寸：50 tokens -> 去除 1 个 CLS 后剩 49 个 -> 7x7 空间方阵。
            grid_size = int(np.sqrt(num_tokens - 1))

            # 1. 重构梯度流: [50, 768] -> 去除 CLS -> [49, 768] -> [7, 7, 768] -> [768, 7, 7]。
            gradients = gradients[1:, :]  # 去除第 0 位 CLS Token。
            gradients = gradients.reshape(grid_size, grid_size, channels).transpose(2, 0, 1)

            # 2. 同步动态重构特征激活流: [50, 768] -> [768, 7, 7]
            if activations.ndim == 2:
                activations = activations[1:, :]
                activations = activations.reshape(grid_size, grid_size, channels).transpose(2, 0, 1)

            print(
                f"[Grad-CAM] 已将 ViT Token 序列恢复为空间特征图: [{channels}, {grid_size}, {grid_size}]")

        # 计算通道权重 (Global Average Pooling 沿空间轴)
        weights = np.mean(gradients, axis=(1, 2))

        # 空间加权求和
        cam = np.zeros(activations.shape[1:], dtype=np.float32)
        for i, w in enumerate(weights):
            cam += w * activations[i]

        # ReLU 过滤（只关注正向促进过拟合/预测的特征），并归一化
        cam = np.maximum(cam, 0)
        if np.max(cam) - np.min(cam) > 1e-8:
            cam = (cam - np.min(cam)) / (np.max(cam) - np.min(cam))
        else:
            cam = np.zeros_like(cam)

        # 映射回原始图像大小并叠加成彩色热力图
        h, w = raw_frame_bgr.shape[:2]
        heatmap = cv2.resize(cam, (w, h))
        heatmap_img = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)

        # 融合原图输出 (60% 原图 + 40% 特征热力图)
        fused_img = cv2.addWeighted(raw_frame_bgr, 0.6, heatmap_img, 0.4, 0)
        return fused_img

    def remove(self):
        for h in self.handlers:
            h.remove()


def map_occlusion_sensitivity(model, single_video_tensor, target_mask, patch_size=24, stride=8):
    """
    显式局部遮挡敏感度映射，用于观察局部区域对预测分数的影响。
    输入单个视频样本的张量 [1, S, 3, 112, 112]，抽取其中一帧进行空间扰动分析。
    """
    _require_cv2()
    model.eval()
    # 选取视频中间具有代表性的一帧进行二维特征探测，假设选取第 10 帧
    frame_idx = min(10, single_video_tensor.size(1) - 1)

    # 1. 提取原始帧并逆规范化回标准的 BGR 图片格式，用于底图绘制
    # 当前数据规范化约定为 mean=0.5, std=0.5，因此反规范化为 img = img * 0.5 + 0.5。
    raw_tensor = single_video_tensor[0, frame_idx].cpu().clone()
    raw_img = (_as_numpy(raw_tensor.permute(1, 2, 0)) * 0.5 + 0.5) * 255.0
    raw_img = np.clip(raw_img, 0, 255).astype(np.uint8)
    raw_img_bgr = cv2.cvtColor(raw_img, cv2.COLOR_RGB2BGR)

    _, S, C, H, W = single_video_tensor.shape

    # 获取无遮挡情况下的基准预测分数
    with torch.no_grad():
        base_bdi, _, _ = model(single_video_tensor.to(model.device), target_mask.to(model.device))
        base_score = base_bdi.item()

    # 初始化敏感度矩阵
    sensitivity_map = np.zeros((H, W), dtype=np.float32)
    count_map = np.zeros((H, W), dtype=np.float32)

    # 2. 二维滑动窗口遮挡模拟
    for y in range(0, H - patch_size + 1, stride):
        for x in range(0, W - patch_size + 1, stride):
            # 克隆当前序列，避免修改原始输入。
            perturbed_video = single_video_tensor.clone()

            # 在指定帧的 (x, y) 位置打上全黑补丁 (因为规范化后 0.0 代表灰色/基准)
            perturbed_video[0, frame_idx, :, y:y + patch_size, x:x + patch_size] = -1.0  # -1.0 对应反规范化后的全黑

            # 重新前向传播
            with torch.no_grad():
                perturbed_bdi, _, _ = model(perturbed_video.to(model.device), target_mask.to(model.device))
                perturbed_score = perturbed_bdi.item()

            # 计算遮挡前后预测值偏离的绝对程度。
            score_gap = abs(perturbed_score - base_score)

            # 累加到覆盖区域
            sensitivity_map[y:y + patch_size, x:x + patch_size] += score_gap
            count_map[y:y + patch_size, x:x + patch_size] += 1.0

    # 3. 归一化并合成投影热力图
    sensitivity_map /= (count_map + 1e-8)
    if np.max(sensitivity_map) - np.min(sensitivity_map) > 1e-8:
        sensitivity_map = (sensitivity_map - np.min(sensitivity_map)) / (
                    np.max(sensitivity_map) - np.min(sensitivity_map))

    heatmap_img = cv2.applyColorMap(np.uint8(255 * sensitivity_map), cv2.COLORMAP_JET)
    # fused_projection = cv2.addWeighted(raw_frame_bgr=raw_img_bgr, alpha=0.6, src2=heatmap_img, beta=0.4, gamma=0)
    fused_projection = cv2.addWeighted(raw_img_bgr, 0.6, heatmap_img, 0.4, 0)
    return fused_projection


class ViTAttentionCAM:
    """
    专门针对 Vision Transformer 的自注意力热力图可视化引擎
    通过替换最后一层注意力模块的 forward，显式保留注意力矩阵用于可视化。
    """

    def __init__(self, model):
        self.model = model
        # 1. 定位最后一层 Transformer 块的自注意力模块。
        self.attn_module = model.backbone.blocks[-1].attn
        self.captured_attn = None

        # 2. 备份原生 forward 方法，以便在 remove() 中恢复。
        self.original_forward = self.attn_module.forward

        # 3. 使用 *args 和 **kwargs 兼容不同 timm 版本传入的可选参数。
        def patched_forward(module_self, x, *args, **kwargs):
            B, N, C = x.shape
            # 自适应获取每个自注意力头的特征维度（Base 模型通常是 768 // 12 = 64）。
            head_dim = getattr(module_self, 'head_dim', C // module_self.num_heads)

            # 展平并解耦出 Query, Key, Value 向量
            qkv = module_self.qkv(x).reshape(B, N, 3, module_self.num_heads, head_dim).permute(2, 0, 3, 1, 4)
            q, k, v = qkv.unbind(0)

            # 显式计算注意力矩阵，避免 fused SDPA 路径隐藏中间权重。
            attn_matrix = (q @ k.transpose(-2, -1)) * module_self.scale

            # 保留 timm 传入的 attn_mask，保证可视化路径与原模型计算一致。
            attn_mask = kwargs.get('attn_mask', None)
            if attn_mask is not None:
                attn_matrix = attn_matrix + attn_mask

            attn_matrix = attn_matrix.softmax(dim=-1)

            # 保存当前批次的自注意力矩阵，供后续热力图生成。
            self.captured_attn = _as_numpy(attn_matrix)

            # 接回原注意力模块的后续投影计算。
            attn_matrix = module_self.attn_drop(attn_matrix)
            out = attn_matrix @ v
            out = out.transpose(1, 2).reshape(B, N, C)
            out = module_self.proj(out)
            out = module_self.proj_drop(out)
            return out

        # 4. 将兼容 forward 绑定到当前模型实例。
        self.attn_module.forward = types.MethodType(patched_forward, self.attn_module)
        print("[ViTAttentionCAM] 已启用显式注意力矩阵捕获。")

    def generate_heatmap(self, raw_img_bgr, frame_idx=10):
        _require_cv2()
        # 前向传播尚未触发时，无法生成注意力热力图。
        if self.captured_attn is None:
            print("[WARNING] 尚未捕获自注意力矩阵，请先执行一次前向传播。")
            return raw_img_bgr

        # 1. 提取对应指定底图帧（如第 10 帧）的自注意力矩阵 [num_heads, 50, 50]
        safe_frame_idx = min(frame_idx, self.captured_attn.shape[0] - 1)
        attn = self.captured_attn[safe_frame_idx]

        # 2. 提取 CLS Token 对后续空间 Patch 的全局自注意力。
        cls_to_patches_attn = attn[:, 0, 1:]

        # 3. 多头语义融合：跨自注意力头求均值
        mean_attn = np.mean(cls_to_patches_attn, axis=0)

        # 4. 空间网格恢复：将 49 个一维表征 Tokens 恢复为 7x7 的面部二维图像方阵
        grid_size = int(np.sqrt(mean_attn.shape[0]))
        cam = mean_attn.reshape(grid_size, grid_size)

        # 5. 极值规范化与高精双线性尺寸拉伸
        cam = cam - np.min(cam)
        cam = cam / (np.max(cam) + 1e-8)
        cam = cv2.resize(cam, (raw_img_bgr.shape[1], raw_img_bgr.shape[0]))

        # 6. OpenCV 色彩热力图融合
        heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
        fused_projection = cv2.addWeighted(raw_img_bgr, 0.6, heatmap, 0.4, 0)

        print(f"[ViTAttentionCAM] 已生成第 {safe_frame_idx} 帧的 CLS 跨头注意力热力图。")
        return fused_projection

    def remove(self):
        # 恢复原始 forward，结束注意力矩阵捕获。
        self.attn_module.forward = self.original_forward
        print("[ViTAttentionCAM] 已恢复原始注意力 forward。")
