DEVICES: [4]
STRATEGY: "auto"

EXTRACT_FEATURE:
  BATCH_SIZE: 1
  CHUNK_SIZE: 32

PROCESS_TEMPORAL:
  MAX_SEQ_LEN: 1000
  MAX_EPOCHS: 2
  FREEZE_EPOCHS: 1
  DISABLE_MULTIVIEW_CONTRASTIVE: True
  CON_LOSS_WEIGHT: 0.0

VISUALIZATION:
  ENABLE: False