MODE: "mtl_lite"
ACCELERATOR: "gpu"
DEVICES: 1
STRATEGY: "auto"
PRECISION: "bf16-mixed"

MODEL:
  NAME: "mtl_lite"
  AUXILIARY_TASKS:
    ORDINAL_CLASSIFICATION: True
    CONTRASTIVE: False
  ENABLE_CGC: False
  ENABLE_ADAPTIVE_MASK: False
  ENABLE_PCGRAD: False
  ENABLE_UNCERTAINTY_WEIGHTING: False

DATASET:
  RETURN_MULTI_VIEW_TRAIN: False

LOSSES:
  REGRESSION: "mse"
  ORDINAL_WEIGHT: 1.0
  CCC_WEIGHT: 0.0
  LDS_WEIGHTING: False
  DIST_WEIGHT: 0.0

VISUALIZATION:
  ENABLE: False
